### PR TITLE
Preview option

### PR DESCRIPTION
**Pull request by niedfelj**

### CODE REVIEW

**Comment by niedfelj** [comment]
This is just a start, don't accept this.

**Comment by dlitvakb** [comment]
Hey @niedfelj,

Thanks for the contribution.

There's a small thing though, even though I really prefer the keyword argument syntax, it's not supported by older ruby versions, which some of our users are indeed using. Therefore introducing a new feature that will break their installations is a no-go.

Please re-write this removing the keyword argument, and use the regular syntax instead.

Cheers

**Comment by niedfelj** [comment]
What versions of Ruby do you officially support and for how long? Keyword arguments were introduced in 2013, seems like it might be time to force clients to upgrade ;) AFAIK, no one officially supports versions less than 2.0 anymore.

https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by niedfelj** [comment]
But yes, I can rewrite without keyword arguments, will take me a while because I also want to integrate pagination and streaming JSON (using yajl...or are you opposed to using that also since it adds another dependency, and a C dependency at that)

**Comment by dlitvakb** [comment]
Introducing new dependencies is a no-go, also, pagination should be left out of this feature, as it's something that introduces breaking changes.

Breaking changes, though welcomed, should not be mixed with simple features that do not break the current behaviour.

Cheers

**Comment by niedfelj** [comment]
Ok, I get it with the dependencies. Not sure I understand how pagination is a breaking change? I definitely agree that each feature should be a different branch or pull request, but I do find it problematic that there are hard limits (1000 entries, assets etc) in the code without a warning or any kind of error that it's not actually dumping all of the content (this is true also in relationships in contentful_model, where I've created another issue)

**Comment by dlitvakb** [comment]
Oh, by pagination you meant on the request to generate json, not on the output file!

Sorry about that. I misunderstood.

Yeah, we can do pagination then.

Cheers

**Pull request closed without merging**
